### ISSUE TITLE
Mail related

### ISSUE THREAD

**Issue by Mastermind-sap** [JDeepD/Open-Palm#15]
For sending a mail with python did you make your mail accept requests from non google services like python or is there a way to authorize just your python file to send emails from your email to prevent making your email vulnerable....?

**Comment by JDeepD** [comment]
I used smtplib for sending mails(which requires to manually disable all the security features that google provides to avoid your email getting hacked). So your email account can actually get hacked by this method.

If you want the security from google, [you have to pay for it](https://workspace.google.com/intl/en_in/pricing.html)

**Comment by Mastermind-sap** [comment]
Ok i was just confirming that stuff...but probably there is a google api which can be used to send mails and it is secure also. check it [here](https://developers.google.com/gmail/api/quickstart/python)

**Comment by JDeepD** [comment]
> Ok i was just confirming that stuff...but probably there is a google api which can be used to send mails and it is secure also. check it [here](https://developers.google.com/gmail/api/quickstart/python)

Thats a good option too
